---
- hosts: all
  tasks:

  - name: update repo index 
    apt:
      update_cache: yes
#
- hosts: api
  strategy: debug
  tasks:

  - name: install docker-compose
    apt:
      name: docker-compose

  - name: Copy files
    synchronize:
      src: "./Dockerized_app/"
      dest: "/usr/src/api"


