- hosts: api
  tasks:

  - name: update repo index 
    apt:
      update_cache: yes

  - name: install docker-compose
    apt:
      name: docker-compose

  - name: Copy files
    synchronize:
      src: "./Dockerized_app/"
      dest: "/usr/src/api"

  - name: run docker compose
    ansible.builtin.command: docker-compose --project-directory /usr/src/api --file /usr/src/api/docker-compose.yml up -d


