#!/bin/bash  

#generate ssh key with no passphrase, dont overwrite and suppress output
ssh-keygen -t rsa -C root -f ./root-ssh-key -q -P "" <<< n  > /dev/null
echo root-ssh-key generated...

terraform init

terraform apply -auto-approve

echo "Ansible starting..."
ansible-playbook -i inventory --key-file ./root-ssh-key --ssh-common-args='-o StrictHostKeyChecking=no' --user root ansible.yml

read -a firstline<inventory
IFS== read -r left ip <<< "${firstline[1]}"
echo "visit http://$ip/"