#!/bin/bash  

#generate ssh key with no passphrase, dont overwrite and suppress output
ssh-keygen -t rsa -C root -f ./root-ssh-key -q -P "" <<< n  > /dev/null
echo root-ssh-key generated...



terraform init

terraform apply -auto-approve
echo terraform applied...

read -r firstline<inventory
echo $firstline

#ansible-playbook -i inventory --key-file ./root-ssh-key --ssh-common-args='-o StrictHostKeyChecking=no' --user root ansible.yml
