version: '3'
services:
    flask:
      build: .
      ports:
        - 80:5000
      volumes: 
        - ./:/app
      env_file:
        - api.env

      command: bash -c 'python set_db.py; python app.py'
     
      restart: always